# Generated by Django 4.2.11 on 2024-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('abilities', models.JSONField()),
                ('wins', models.BigIntegerField()),
                ('losses', models.BigIntegerField()),
                ('kills', models.BigIntegerField()),
                ('deaths', models.BigIntegerField()),
                ('assists', models.BigIntegerField()),
            ],
        ),
    ]
