# Generated by Django 4.2.11 on 2025-04-03 00:27

import apps.players.Models.PlayerHeroModel
import apps.players.Models.PlayerModel
import apps.players.Models.PlayerRecords
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHeroModel',
            fields=[
                ('player_hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id3', models.BigIntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('wins', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('souls', models.BigIntegerField(default=0)),
                ('soulsPerMin', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('heroCritPercent', models.FloatField(default=0)),
                ('heroDamage', models.BigIntegerField(default=0)),
                ('objDamage', models.BigIntegerField(default=0)),
                ('healing', models.BigIntegerField(default=0)),
                ('laneCreeps', models.IntegerField(default=0)),
                ('neutralCreeps', models.IntegerField(default=0)),
                ('lastHits', models.IntegerField(default=0)),
                ('denies', models.IntegerField(default=0)),
                ('multis', models.JSONField(default=apps.players.Models.PlayerHeroModel.default_multis, null=True)),
                ('streaks', models.JSONField(default=apps.players.Models.PlayerHeroModel.default_streaks, null=True)),
                ('longestStreak', models.IntegerField(default=0)),
                ('guardians', models.IntegerField(default=0)),
                ('walkers', models.IntegerField(default=0)),
                ('baseGuardians', models.IntegerField(default=0)),
                ('shieldGenerators', models.IntegerField(default=0)),
                ('titans', models.IntegerField(default=0)),
                ('patrons', models.IntegerField(default=0)),
                ('midbosses', models.IntegerField(default=0)),
                ('rejuvinators', models.IntegerField(default=0)),
                ('tier', models.IntegerField(null=True)),
                ('beta', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('player_id', models.IntegerField()),
                ('steam_id3', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.JSONField(null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('private', models.BooleanField(default=False)),
                ('rank', models.IntegerField(null=True)),
                ('wins', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('souls', models.BigIntegerField(default=0)),
                ('soulsPerMin', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('heroCritPercent', models.FloatField(default=0)),
                ('heroDamage', models.BigIntegerField(default=0)),
                ('objDamage', models.BigIntegerField(default=0)),
                ('healing', models.BigIntegerField(default=0)),
                ('guardians', models.IntegerField(default=0)),
                ('walkers', models.IntegerField(default=0)),
                ('baseGuardians', models.IntegerField(default=0)),
                ('shieldGenerators', models.IntegerField(default=0)),
                ('patrons', models.IntegerField(default=0)),
                ('midbosses', models.IntegerField(default=0)),
                ('rejuvinators', models.IntegerField(default=0)),
                ('laneCreeps', models.IntegerField(default=0)),
                ('neutralCreeps', models.IntegerField(default=0)),
                ('lastHits', models.IntegerField(default=0)),
                ('denies', models.IntegerField(default=0)),
                ('multis', models.JSONField(default=apps.players.Models.PlayerModel.default_multis, null=True)),
                ('streaks', models.JSONField(default=apps.players.Models.PlayerModel.default_streaks, null=True)),
                ('longestStreak', models.IntegerField(default=0)),
                ('mmr', models.BigIntegerField(default=0)),
                ('lastLogin', models.BigIntegerField(blank=True, null=True)),
                ('timePlayed', models.IntegerField(blank=True, null=True)),
                ('created', models.BigIntegerField(blank=True, default=apps.players.Models.PlayerModel.current_timestamp, null=True)),
                ('updated', models.BigIntegerField(null=True)),
                ('inactive', models.BooleanField(default=True)),
                ('matches', models.ManyToManyField(related_name='playerModel', to='matches.matchesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.JSONField(default=apps.players.Models.PlayerRecords.default_records, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playermodel')),
            ],
        ),
    ]
