# Generated by Django 4.2.11 on 2025-01-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('heroes', '0007_alter_heroesmodel_beta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id3', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('player_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('wins', models.BigIntegerField(default=0)),
                ('losses', models.BigIntegerField(default=0)),
                ('kills', models.BigIntegerField(default=0)),
                ('deaths', models.BigIntegerField(default=0)),
                ('assists', models.BigIntegerField(default=0)),
                ('souls', models.BigIntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('heroDamage', models.BigIntegerField(default=0)),
                ('objDamage', models.BigIntegerField(default=0)),
                ('healing', models.BigIntegerField(default=0)),
                ('doubleKills', models.BigIntegerField(default=0)),
                ('tripleKills', models.BigIntegerField(default=0)),
                ('quadKills', models.BigIntegerField(default=0)),
                ('pentaKills', models.BigIntegerField(default=0)),
                ('ultraKills', models.BigIntegerField(default=0)),
                ('threeStreak', models.BigIntegerField(default=0)),
                ('fourStreak', models.BigIntegerField(default=0)),
                ('fiveStreak', models.BigIntegerField(default=0)),
                ('sixStreak', models.BigIntegerField(default=0)),
                ('sevenStreak', models.BigIntegerField(default=0)),
                ('eightStreak', models.BigIntegerField(default=0)),
                ('nineStreak', models.BigIntegerField(default=0)),
                ('tenStreak', models.BigIntegerField(default=0)),
                ('mmr', models.BigIntegerField(default=0)),
                ('lastMatch', models.DateTimeField(null=True)),
                ('lastLogin', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timelineTracking', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(related_name='playersModel', to='matches.matchesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHeroModel',
            fields=[
                ('player_hero_id', models.AutoField(primary_key=True, serialize=False)),
                ('wins', models.BigIntegerField(default=0)),
                ('losses', models.BigIntegerField(default=0)),
                ('kills', models.BigIntegerField(default=0)),
                ('deaths', models.BigIntegerField(default=0)),
                ('assists', models.BigIntegerField(default=0)),
                ('souls', models.BigIntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('matches', models.BigIntegerField(default=0)),
                ('heroDamage', models.BigIntegerField(default=0)),
                ('objDamage', models.BigIntegerField(default=0)),
                ('healing', models.BigIntegerField(default=0)),
                ('doubleKills', models.BigIntegerField(default=0)),
                ('tripleKills', models.BigIntegerField(default=0)),
                ('quadKills', models.BigIntegerField(default=0)),
                ('pentaKills', models.BigIntegerField(default=0)),
                ('ultraKills', models.BigIntegerField(default=0)),
                ('threeStreak', models.BigIntegerField(default=0)),
                ('fourStreak', models.BigIntegerField(default=0)),
                ('fiveStreak', models.BigIntegerField(default=0)),
                ('sixStreak', models.BigIntegerField(default=0)),
                ('sevenStreak', models.BigIntegerField(default=0)),
                ('eightStreak', models.BigIntegerField(default=0)),
                ('nineStreak', models.BigIntegerField(default=0)),
                ('tenStreak', models.BigIntegerField(default=0)),
                ('tier', models.CharField(max_length=1, null=True)),
                ('beta', models.BooleanField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_hero_stats', to='heroes.heroesmodel')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_hero_stats', to='players.playermodel')),
            ],
        ),
    ]
