# Generated by Django 4.2.11 on 2025-04-03 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_hero_stats', to='heroes.heroesmodel'),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_hero_stats', to='players.playermodel'),
        ),
    ]
