# Generated by Django 4.2.11 on 2025-03-19 23:17

import apps.players.Models.PlayerRecords
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerheromodel',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='baseGuardians',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='guardians',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='midbosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='patrons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='rejuvinators',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='shieldGenerators',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='walkers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerrecords',
            name='records',
            field=models.JSONField(default=apps.players.Models.PlayerRecords.default_records, null=True),
        ),
    ]
