# Generated by Django 4.2.11 on 2025-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='player_id',
            field=models.IntegerField(null=True),
        ),
    ]
