# Generated by Django 4.2.11 on 2025-01-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_player_id_playerheromodel_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='midbosses',
            field=models.IntegerField(default=0),
        ),
    ]
