# Generated by Django 4.2.11 on 2025-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playermodel_midbosses'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerheromodel',
            name='denies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='heroCritPercent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='lastHits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='heroCritPercent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playerheromodel',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
