# Generated by Django 4.2.11 on 2025-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerheromodel_denies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerheromodel',
            name='laneCreeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='neutralCreeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='denies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='laneCreeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='neutralCreeps',
            field=models.IntegerField(default=0),
        ),
    ]
