# Generated by Django 4.2.11 on 2025-01-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playerheromodel_lanecreeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerheromodel',
            name='soulsPerMin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='rejuvinators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='soulsPerMin',
            field=models.FloatField(default=0),
        ),
    ]
