# Generated by Django 4.2.11 on 2025-01-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerheromodel_soulspermin_playermodel_rejuvinators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='timePlayed',
            field=models.IntegerField(null=True),
        ),
    ]
