# Generated by Django 4.2.11 on 2025-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_matchplayermodel_soulspermin'),
        ('players', '0007_playermodel_timeplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='lastMatch',
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='player_tag',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerheromodel',
            name='tier',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='avatar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='matches',
            field=models.ManyToManyField(related_name='playerModel', to='matches.matchesmodel'),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='region',
            field=models.CharField(max_length=2),
        ),
    ]
