# Generated by Django 4.2.11 on 2025-01-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_playermodel_lastmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='avatar',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='icon',
            field=models.JSONField(null=True),
        ),
    ]
