# Generated by Django 4.2.11 on 2025-02-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_remove_playermodel_avatar_playermodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='region',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
