# Generated by Django 4.2.11 on 2025-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_playermodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='multis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='region',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='streaks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='timePlayed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
