# Generated by Django 4.2.11 on 2025-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_playermodel_lastlogin_alter_playermodel_multis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='updated',
            field=models.BigIntegerField(blank=True),
        ),
    ]
