# Generated by Django 4.2.11 on 2025-02-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_playermodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='updated',
            field=models.BigIntegerField(null=True),
        ),
    ]
