# Generated by Django 4.2.11 on 2025-02-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_playermodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='multis',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='steam_id3',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='streaks',
            field=models.JSONField(null=True),
        ),
    ]
