# Generated by Django 4.2.11 on 2025-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_playermodel_multis_alter_playermodel_steam_id3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='baseGuardians',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='guardians',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='midbosses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='patrons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='rejuvinators',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='shieldGenerators',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='walkers',
            field=models.IntegerField(null=True),
        ),
    ]
