# Generated by Django 4.2.11 on 2025-02-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0015_alter_playermodel_baseguardians_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='timelineTracking',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='lastLogin',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playermodel')),
            ],
        ),
    ]
