# Generated by Django 4.2.11 on 2025-02-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_remove_playermodel_timelinetracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='created',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
