# Generated by Django 4.2.11 on 2025-02-20 05:16

import apps.players.Models.PlayerModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_alter_playermodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='created',
            field=models.BigIntegerField(blank=True, default=apps.players.Models.PlayerModel.current_timestamp, null=True),
        ),
    ]
