# Generated by Django 4.2.11 on 2025-02-21 21:41

import apps.players.Models.PlayerHeroModel
import apps.players.Models.PlayerModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_alter_playermodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerheromodel',
            name='midBoss',
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='baseGuardians',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='guardians',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='midbosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='patrons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='rejuvinators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='shieldGenerators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='steam_id3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='titans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerheromodel',
            name='walkers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerheromodel',
            name='multis',
            field=models.JSONField(default=apps.players.Models.PlayerHeroModel.default_multis, null=True),
        ),
        migrations.AlterField(
            model_name='playerheromodel',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_hero_stats', to='players.playermodel'),
        ),
        migrations.AlterField(
            model_name='playerheromodel',
            name='streaks',
            field=models.JSONField(default=apps.players.Models.PlayerHeroModel.default_streaks, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='multis',
            field=models.JSONField(default=apps.players.Models.PlayerModel.default_multis, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='streaks',
            field=models.JSONField(default=apps.players.Models.PlayerModel.default_streaks, null=True),
        ),
    ]
