# Generated by Django 4.2.11 on 2025-04-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('className', models.CharField(max_length=100, null=True)),
                ('hero_deadlock_id', models.IntegerField(null=True, unique=True)),
                ('rank', models.IntegerField(null=True)),
                ('description', models.JSONField(null=True)),
                ('abilities', models.JSONField(null=True)),
                ('wins', models.BigIntegerField(null=True)),
                ('losses', models.BigIntegerField(null=True)),
                ('kills', models.BigIntegerField(null=True)),
                ('deaths', models.BigIntegerField(null=True)),
                ('assists', models.BigIntegerField(null=True)),
                ('matches', models.BigIntegerField(null=True)),
                ('pickrate', models.IntegerField(null=True)),
                ('tier', models.CharField(max_length=1, null=True)),
                ('beta', models.BooleanField(null=True)),
                ('images', models.JSONField(null=True)),
            ],
        ),
    ]
