# Generated by Django 4.2.11 on 2024-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroesmodel',
            name='abilities',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='assists',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='deaths',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='kills',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='losses',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='wins',
            field=models.BigIntegerField(null=True),
        ),
    ]
