# Generated by Django 4.2.11 on 2024-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_heroesmodel_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='matches',
            field=models.BigIntegerField(null=True),
        ),
    ]
