# Generated by Django 4.2.11 on 2024-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_heroesmodel_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='tier',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
