# Generated by Django 4.2.11 on 2024-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_heroesmodel_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='pickrate',
            field=models.IntegerField(null=True),
        ),
    ]
