# Generated by Django 4.2.11 on 2024-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_heroesmodel_pickrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='beta',
            field=models.BooleanField(default=False),
        ),
    ]
