# Generated by Django 4.2.11 on 2024-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_heroesmodel_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroesmodel',
            name='beta',
            field=models.BooleanField(null=True),
        ),
    ]
