# Generated by Django 4.2.11 on 2025-01-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_alter_heroesmodel_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='dl_hero_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
