# Generated by Django 4.2.11 on 2025-01-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_heroesmodel_dl_hero_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroesmodel',
            old_name='dl_hero_id',
            new_name='hero_deadlock_id',
        ),
    ]
