# Generated by Django 4.2.11 on 2025-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_rename_dl_hero_id_heroesmodel_hero_deadlock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='className',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroesmodel',
            name='images',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='heroesmodel',
            name='description',
            field=models.JSONField(null=True),
        ),
    ]
