# Generated by Django 4.2.11 on 2025-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_heroesmodel_classname_heroesmodel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesmodel',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
