# Generated by Django 4.2.11 on 2025-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        ('players', '0002_initial'),
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='match_favorites',
            field=models.ManyToManyField(blank=True, related_name='match_favorites', to='matches.matchesmodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='player_favorites', to='players.playermodel'),
        ),
    ]
