from django.db import models
from .MatchesModel import MatchesModel
from ...players.Models.PlayerModel import PlayerModel

class MatchPlayerModel(models.Model):
    match_player_id = models.AutoField(primary_key=True)
    steam_id3 = models.BigIntegerField()
    match = models.ForeignKey(MatchesModel, related_name='matchPlayerModels', on_delete=models.CASCADE)
    player = models.ForeignKey(PlayerModel, related_name='matchPlayerModels', on_delete=models.CASCADE, null=True)
    party = models.IntegerField(default=0)
    playerSlot = models.IntegerField(default=0)
    hero = models.CharField(max_length=100, null=True)
    team = models.CharField(max_length=100, null=True)
    lane = models.IntegerField(null=True)
    kills = models.IntegerField(default=0)
    deaths = models.IntegerField(default=0)
    assists = models.IntegerField(default=0)
    souls = models.BigIntegerField(default=0)
    soulsBreakdown = models.JSONField(null=True)
    level = models.IntegerField(default=0)
    accuracy = models.FloatField(default=0)
    heroDamage = models.IntegerField(default=0)
    objDamage = models.IntegerField(default=0)
    healing = models.IntegerField(default=0)
    lastHits = models.IntegerField(default=0)
    denies = models.IntegerField(default=0)
    items = models.JSONField(null=True)
    abilities = models.JSONField(null=True)
    win = models.BooleanField(default=0)
    medals = models.JSONField(null=True)
    abandoned = models.BooleanField(default=False)
    abandonedTime = models.BigIntegerField(default=0)
