# Generated by Django 4.2.11 on 2025-03-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesModel',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadlock_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('date', models.BigIntegerField(null=True)),
                ('averageRank', models.JSONField(null=True)),
                ('gameMode', models.CharField(max_length=50, null=True)),
                ('matchMode', models.CharField(max_length=50, null=True)),
                ('length', models.IntegerField(default=0)),
                ('teamStats', models.JSONField(null=True)),
                ('victor', models.CharField(max_length=50, null=True)),
                ('legacyFourLaneMap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id3', models.BigIntegerField()),
                ('timestamp', models.IntegerField()),
                ('net_worth', models.IntegerField(null=True)),
                ('player_damage', models.IntegerField(null=True)),
                ('boss_damage', models.IntegerField(null=True)),
                ('player_healing', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerModel',
            fields=[
                ('match_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id3', models.BigIntegerField()),
                ('party', models.IntegerField(default=0)),
                ('playerSlot', models.IntegerField(default=0)),
                ('hero_deadlock_id', models.IntegerField(null=True)),
                ('team', models.CharField(max_length=50, null=True)),
                ('lane', models.IntegerField(null=True)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('souls', models.IntegerField(default=0)),
                ('soulsBreakdown', models.JSONField(null=True)),
                ('soulsPerMin', models.FloatField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('heroCritPercent', models.FloatField(default=0)),
                ('heroDamage', models.IntegerField(default=0)),
                ('objDamage', models.IntegerField(default=0)),
                ('healing', models.IntegerField(default=0)),
                ('laneCreeps', models.IntegerField(default=0)),
                ('neutralCreeps', models.IntegerField(default=0)),
                ('lastHits', models.IntegerField(default=0)),
                ('denies', models.IntegerField(default=0)),
                ('items', models.JSONField(null=True)),
                ('abilities', models.JSONField(null=True)),
                ('multis', models.JSONField(null=True)),
                ('streaks', models.JSONField(null=True)),
                ('win', models.BooleanField(default=0)),
                ('medals', models.JSONField(null=True)),
                ('longestStreak', models.IntegerField(default=0)),
                ('abandoned', models.BooleanField(default=False)),
                ('abandonedTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PvPEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('slayer_hero_id', models.IntegerField()),
                ('victim_hero_id', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('target', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidbossEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('slayer', models.CharField(max_length=50, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerTimelineEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=10, null=True)),
                ('details', models.JSONField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='matches.matchesmodel')),
            ],
        ),
    ]
