# Generated by Django 4.2.11 on 2025-01-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesModel',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadlock_id', models.BigIntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('averageRank', models.JSONField(null=True)),
                ('gameMode', models.CharField(max_length=50, null=True)),
                ('matchMode', models.CharField(max_length=50, null=True)),
                ('length', models.IntegerField(default=0)),
                ('teamStats', models.JSONField(null=True)),
                ('victor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerModel',
            fields=[
                ('match_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id3', models.BigIntegerField()),
                ('party', models.IntegerField(default=0)),
                ('playerSlot', models.IntegerField(default=0)),
                ('hero', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('lane', models.IntegerField(null=True)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('souls', models.BigIntegerField(default=0)),
                ('soulsBreakdown', models.JSONField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('heroDamage', models.IntegerField(default=0)),
                ('objDamage', models.IntegerField(default=0)),
                ('healing', models.IntegerField(default=0)),
                ('lastHits', models.IntegerField(default=0)),
                ('denies', models.IntegerField(default=0)),
                ('items', models.JSONField(null=True)),
                ('abilities', models.JSONField(null=True)),
                ('multiKills', models.JSONField(null=True)),
                ('streaks', models.JSONField(null=True)),
                ('win', models.BooleanField(default=0)),
                ('medals', models.JSONField(null=True)),
                ('abandoned', models.BooleanField(default=False)),
                ('abandonedTime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerTimelineEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('eventType', models.CharField(max_length=100, null=True)),
                ('eventData', models.JSONField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='matches.matchesmodel')),
            ],
        ),
    ]
