# Generated by Django 4.2.11 on 2025-04-03 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayertimelineevent',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='players.playermodel'),
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerModels', to='matches.matchesmodel'),
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerModels', to='players.playermodel'),
        ),
        migrations.AddField(
            model_name='matchplayergraph',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matchesmodel'),
        ),
        migrations.AddIndex(
            model_name='matchplayermodel',
            index=models.Index(fields=['steam_id3', 'match'], name='matches_mat_steam_i_a51cdb_idx'),
        ),
    ]
