# Generated by Django 4.2.11 on 2025-01-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayertimelineevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='players.playermodel'),
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerModels', to='matches.matchesmodel'),
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerModels', to='players.playermodel'),
        ),
    ]
