# Generated by Django 4.2.11 on 2025-01-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvPEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('slayer_hero_id', models.IntegerField()),
                ('victim_hero_id', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('target', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidbossEvent',
            fields=[
                ('timeline_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50, null=True)),
                ('slayer', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='matches.matchesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
