# Generated by Django 4.2.11 on 2025-03-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesmodel',
            name='legacyFourLaneMap',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchesmodel',
            name='length',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
