# Generated by Django 4.2.11 on 2025-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesmodel',
            name='match_id',
            field=models.IntegerField(null=True),
        ),
    ]
