# Generated by Django 4.2.11 on 2025-06-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matchesmodel_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesmodel',
            name='botGame',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
