# Generated by Django 4.2.11 on 2025-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_pvpevent_objectiveevent_midbossevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midbossevent',
            name='slayer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='objectiveevent',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
