# Generated by Django 4.2.11 on 2025-01-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_midbossevent_slayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayermodel',
            old_name='multiKills',
            new_name='multis',
        ),
        migrations.RemoveField(
            model_name='matchplayermodel',
            name='hero',
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='dl_hero_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayermodel',
            name='abandonedTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchplayermodel',
            name='souls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchplayermodel',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
