# Generated by Django 4.2.11 on 2025-01-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_rename_multikills_matchplayermodel_multis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayermodel',
            old_name='dl_hero_id',
            new_name='hero_deadlock_id',
        ),
    ]
