# Generated by Django 4.2.11 on 2025-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_rename_dl_hero_id_matchplayermodel_hero_deadlock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayermodel',
            name='heroCritPercent',
            field=models.FloatField(default=0),
        ),
    ]
