# Generated by Django 4.2.11 on 2025-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchplayermodel_herocritpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayermodel',
            name='laneCreeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayermodel',
            name='neutralCreeps',
            field=models.IntegerField(default=0),
        ),
    ]
