# Generated by Django 4.2.11 on 2025-01-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_matchplayermodel_lanecreeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayermodel',
            name='soulsPerMin',
            field=models.FloatField(default=0),
        ),
    ]
