# Generated by Django 4.2.11 on 2025-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_matchplayermodel_soulspermin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesmodel',
            name='deadlock_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
