# Generated by Django 4.2.11 on 2025-02-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_matchesmodel_deadlock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesmodel',
            name='deadlock_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='matchplayermodel',
            index=models.Index(fields=['steam_id3', 'match'], name='matches_mat_steam_i_a51cdb_idx'),
        ),
    ]
