# Generated by Django 4.2.11 on 2025-02-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_matchesmodel_deadlock_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesmodel',
            name='date',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MatchPlayerGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id3', models.BigIntegerField(unique=True)),
                ('timestamp', models.IntegerField()),
                ('net_worth', models.IntegerField(null=True)),
                ('player_damage', models.IntegerField(null=True)),
                ('boss_damage', models.IntegerField(null=True)),
                ('player_healing', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matchesmodel')),
            ],
        ),
    ]
