# Generated by Django 4.2.11 on 2025-02-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_matchesmodel_date_matchplayergraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayergraph',
            name='steam_id3',
            field=models.BigIntegerField(),
        ),
    ]
