# Generated by Django 4.2.11 on 2025-02-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_matchplayergraph_steam_id3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayertimelineevent',
            old_name='eventData',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='matchplayertimelineevent',
            name='eventType',
        ),
        migrations.RemoveField(
            model_name='matchplayertimelineevent',
            name='player',
        ),
        migrations.AddField(
            model_name='matchplayertimelineevent',
            name='matchPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='matches.matchplayermodel'),
        ),
        migrations.AddField(
            model_name='matchplayertimelineevent',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
