# Generated by Django 4.2.11 on 2025-02-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_rename_eventdata_matchplayertimelineevent_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayertimelineevent',
            name='matchPlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='matches.matchplayermodel'),
        ),
    ]
