# Generated by Django 4.2.11 on 2025-02-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_remove_playermodel_timelinetracking_and_more'),
        ('matches', '0016_midbossevent_content_type_midbossevent_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchplayertimelineevent',
            name='matchPlayer',
        ),
        migrations.AddField(
            model_name='matchplayertimelineevent',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchPlayerTimelineEvents', to='players.playermodel'),
        ),
    ]
