# Generated by Django 4.2.11 on 2025-02-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_remove_matchplayertimelineevent_matchplayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midbossevent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='midbossevent',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='objectiveevent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='objectiveevent',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='pvpevent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pvpevent',
            name='object_id',
        ),
    ]
