# Generated by Django 4.2.11 on 2025-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_remove_midbossevent_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midbossevent',
            name='slayer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
