# Generated by Django 4.2.11 on 2025-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_alter_midbossevent_slayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayermodel',
            name='longestStreak',
            field=models.IntegerField(default=0),
        ),
    ]
