# Generated by Django 4.2.11 on 2025-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_matchplayermodel_longeststreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesmodel',
            name='legacyFourLaneMap',
            field=models.BooleanField(default=False),
        ),
    ]
